apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
  creationTimestamp: "2024-12-04T11:17:46Z"
  generation: 1
  name: macvlan-conf
  namespace: fluidos
  resourceVersion: "1353741"
  uid: a8427100-0f24-4dc9-a04f-70ff72e3aa9b
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "ens18", "mode": "bridge",
    "ipam": { "type": "host-local", "subnet": "10.200.0.0/24", "rangeStart": "10.200.0.101",
    "rangeEnd": "10.200.0.101" } }'
